const img = {
	bg: "bg",
	chef: "chef",
	G: "G",
	gallery01: "gallery01",
	gallery02: "gallery02",
	gallery03: "gallery03",
	gallery04: "gallery04",
	knife: "knife",
	logo: "logo",
	menu: "menu",
	overlaybg: "overlaybg",
	spoon: "spoon",
	welcome: "welcome",
	findus: "findus",
	laurels: "laurels",
	award01: "award01",
	award02: "award02",
	award03: "award03",
	award05: "award05",
	sign: "sign",
	quote: "quote",
	gericht: "gericht",
};

export default img;
